In [120]:
import numpy as np

In [121]:
# definindo um número complexo
a = 5 + 3j
print(a)

(5+3j)


In [122]:
# módulo de a
abs(a)

5.830951894845301

In [123]:
# divisão de 2 números complexo
(5 + 3j) / (3 + 1j)

(1.7999999999999998+0.4j)

In [124]:
# parte real de a
a.real

5.0

In [125]:
# parte imaginária de a
a.imag

3.0

In [126]:
# conjugado do a
np.conjugate(a) # ou np.conj(a)  

(5-3j)

In [127]:
# vetor do tipo linha
v0l = np.array([[1, 0]])
print(v0l)

[[1 0]]


In [128]:
# vetor do tipo coluna
v0c = np.array([[1], [0]])
v0c

array([[1],
       [0]])

In [129]:
# produto de vetores ou matrizes
# escalar
v0l @ v0c

array([[1]])

In [130]:
# matriz
v0c @ v0l

array([[1, 0],
       [0, 0]])

In [131]:
v0c

array([[1],
       [0]])

In [132]:
v1c = np.array([[0],[1]])
v1c

array([[0],
       [1]])

In [133]:
psi = (3 + 1j) * v0c / np.sqrt(39) + (5 - 2j) * v1c / np.sqrt(39)
psi

array([[0.48038446+0.16012815j],
       [0.80064077-0.32025631j]])

In [134]:
np.conj(psi)

array([[0.48038446-0.16012815j],
       [0.80064077+0.32025631j]])

In [135]:
# transposto complexo conjugado
psid = np.transpose(np.conj(psi))
psid

array([[0.48038446-0.16012815j, 0.80064077+0.32025631j]])

In [136]:
psid@psi

array([[1.+0.j]])

In [137]:
psi@psid

array([[0.25641026+0.j        , 0.33333333+0.28205128j],
       [0.33333333-0.28205128j, 0.74358974+0.j        ]])

In [138]:
Sz = np.array([[1, 0], [0, -1]])
Sz

array([[ 1,  0],
       [ 0, -1]])

In [139]:
psi

array([[0.48038446+0.16012815j],
       [0.80064077-0.32025631j]])

In [140]:
Sz @ psi

array([[ 0.48038446+0.16012815j],
       [-0.80064077+0.32025631j]])

In [141]:
Sx = np.array([[0, 1],[1, 0]])
Sx

array([[0, 1],
       [1, 0]])

In [142]:
Sx @ psi

array([[0.80064077-0.32025631j],
       [0.48038446+0.16012815j]])